pluginManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'net.neoforged.moddev' version '2.0.144' apply false
}

rootProject.name = 'ExtremeCraftingTable'